=begin
#OpenAPI Documentation for Ejabberd HTTP APIs

#APIs for managing Ejabberd server

The version of the OpenAPI document: 1.0.0


OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for EjabberdHttpClient::ConfigApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ConfigApi' do
  before do
    # run before each test
    @api_instance = EjabberdHttpClient::ConfigApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ConfigApi' do
    it 'should create an instance of ConfigApi' do
      expect(@api_instance).to be_instance_of(EjabberdHttpClient::ConfigApi)
    end
  end

  # unit tests for convert_to_yaml
  # Convert the input configuration file from Erlang to YAML format.
  # @param convert_to_yaml_request
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'convert_to_yaml test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for dump_config
  # Dump configuration in YAML format as seen by ejabberd.
  # @param dump_config_request
  # @param [Hash] opts the optional parameters
  # @return [Integer]
  describe 'dump_config test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reload_config
  # Reload config file in memory.
  # @param [Hash] opts the optional parameters
  # @return [Integer]
  describe 'reload_config test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
