=begin
#OpenAPI Documentation for Ejabberd HTTP APIs

#APIs for managing Ejabberd server

The version of the OpenAPI document: 1.0.0


OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for EjabberdHttpClient::DocumentationApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DocumentationApi' do
  before do
    # run before each test
    @api_instance = EjabberdHttpClient::DocumentationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DocumentationApi' do
    it 'should create an instance of DocumentationApi' do
      expect(@api_instance).to be_instance_of(EjabberdHttpClient::DocumentationApi)
    end
  end

  # unit tests for gen_html_doc_for_commands
  # Generates html documentation for ejabberd_commands.
  # @param gen_html_doc_for_commands_request
  # @param [Hash] opts the optional parameters
  # @return [Integer]
  describe 'gen_html_doc_for_commands test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for gen_markdown_doc_for_commands
  # Generates markdown documentation for ejabberd_commands.
  # @param gen_html_doc_for_commands_request
  # @param [Hash] opts the optional parameters
  # @return [Integer]
  describe 'gen_markdown_doc_for_commands test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for gen_markdown_doc_for_tags
  # Generates markdown documentation for ejabberd_commands.
  # @param gen_markdown_doc_for_tags_request
  # @param [Hash] opts the optional parameters
  # @return [Integer]
  describe 'gen_markdown_doc_for_tags test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for generate_manpage
  # Generate Unix manpage for current ejabberd version.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'generate_manpage test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
