=begin
#OpenAPI Documentation for Ejabberd HTTP APIs

#APIs for managing Ejabberd server

The version of the OpenAPI document: 1.0.0


OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for EjabberdHttpClient::MamApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MamApi' do
  before do
    # run before each test
    @api_instance = EjabberdHttpClient::MamApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MamApi' do
    it 'should create an instance of MamApi' do
      expect(@api_instance).to be_instance_of(EjabberdHttpClient::MamApi)
    end
  end

  # unit tests for remove_mam_for_user
  # Remove mam archive for user.
  # @param [Hash] opts the optional parameters
  # @option opts [GetOfflineCountRequest] :get_offline_count_request
  # @return [String]
  describe 'remove_mam_for_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for remove_mam_for_user_with_peer
  # Remove mam archive for user with peer.
  # @param [Hash] opts the optional parameters
  # @option opts [RemoveMamForUserWithPeerRequest] :remove_mam_for_user_with_peer_request
  # @return [String]
  describe 'remove_mam_for_user_with_peer test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
