=begin
#OpenAPI Documentation for Ejabberd HTTP APIs

#APIs for managing Ejabberd server

The version of the OpenAPI document: 1.0.0


OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for EjabberdHttpClient::OauthApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OauthApi' do
  before do
    # run before each test
    @api_instance = EjabberdHttpClient::OauthApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OauthApi' do
    it 'should create an instance of OauthApi' do
      expect(@api_instance).to be_instance_of(EjabberdHttpClient::OauthApi)
    end
  end

  # unit tests for add_o_auth_client_implicit
  # Add OAUTH client_id with implicit grant type.
  # @param add_o_auth_client_implicit_request
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'add_o_auth_client_implicit test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for add_o_auth_client_password
  # Add OAUTH client_id with password grant type.
  # @param add_o_auth_client_password_request
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'add_o_auth_client_password test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for issue_o_auth_token
  # Issue an oauth token for the given jid.
  # @param issue_o_auth_token_request
  # @param [Hash] opts the optional parameters
  # @return [IssueOAuthToken200Response]
  describe 'issue_o_auth_token test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_o_auth_tokens
  # List OAuth tokens, their users and scopes, and their time until expiration.
  # @param [Hash] opts the optional parameters
  # @return [Array<ListOAuthTokens200ResponseInner>]
  describe 'list_o_auth_tokens test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for remove_o_auth_client
  # Remove an OAuth client_id.
  # @param remove_o_auth_client_request
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'remove_o_auth_client test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for revoke_o_auth_token
  # Revoke an existing OAuth token.
  # @param revoke_o_auth_token_request
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'revoke_o_auth_token test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
