=begin
#OpenAPI Documentation for Ejabberd HTTP APIs

#APIs for managing Ejabberd server

The version of the OpenAPI document: 1.0.0


OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for EjabberdHttpClient::OfflineApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OfflineApi' do
  before do
    # run before each test
    @api_instance = EjabberdHttpClient::OfflineApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OfflineApi' do
    it 'should create an instance of OfflineApi' do
      expect(@api_instance).to be_instance_of(EjabberdHttpClient::OfflineApi)
    end
  end

  # unit tests for get_offline_count
  # Get the number of unread offline messages.
  # @param get_offline_count_request
  # @param [Hash] opts the optional parameters
  # @return [GetOfflineCount200Response]
  describe 'get_offline_count test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
