=begin
#OpenAPI Documentation for Ejabberd HTTP APIs

#APIs for managing Ejabberd server

The version of the OpenAPI document: 1.0.0


OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for EjabberdHttpClient::PrivateApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PrivateApi' do
  before do
    # run before each test
    @api_instance = EjabberdHttpClient::PrivateApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PrivateApi' do
    it 'should create an instance of PrivateApi' do
      expect(@api_instance).to be_instance_of(EjabberdHttpClient::PrivateApi)
    end
  end

  # unit tests for bookmarks_to_pep
  # Export private XML storage bookmarks to PEP.
  # @param bookmarks_to_pep_request
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'bookmarks_to_pep test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for private_get
  # Get some information from a user private storage.
  # @param [Hash] opts the optional parameters
  # @option opts [PrivateGetRequest] :private_get_request
  # @return [ImportDir200Response]
  describe 'private_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for private_set
  # Set to the user private storage.
  # @param [Hash] opts the optional parameters
  # @option opts [PrivateSetRequest] :private_set_request
  # @return [Integer]
  describe 'private_set test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
