=begin
#OpenAPI Documentation for Ejabberd HTTP APIs

#APIs for managing Ejabberd server

The version of the OpenAPI document: 1.0.0


OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for EjabberdHttpClient::S2sApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'S2sApi' do
  before do
    # run before each test
    @api_instance = EjabberdHttpClient::S2sApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of S2sApi' do
    it 'should create an instance of S2sApi' do
      expect(@api_instance).to be_instance_of(EjabberdHttpClient::S2sApi)
    end
  end

  # unit tests for get_outgoing_s2s_number
  # Number of outgoing s2s connections on the node.
  # @param [Hash] opts the optional parameters
  # @return [GetOutgoingS2sNumber200Response]
  describe 'get_outgoing_s2s_number test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for incoming_s2s_number
  # Number of incoming s2s connections on the node.
  # @param [Hash] opts the optional parameters
  # @return [IncomingS2sNumber200Response]
  describe 'incoming_s2s_number test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for stop_s2s_connections
  # Stop all s2s outgoing and incoming connections.
  # @param [Hash] opts the optional parameters
  # @return [Integer]
  describe 'stop_s2s_connections test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
