=begin
#OpenAPI Documentation for Ejabberd HTTP APIs

#APIs for managing Ejabberd server

The version of the OpenAPI document: 1.0.0


OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for EjabberdHttpClient::SharedRosterGroupApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SharedRosterGroupApi' do
  before do
    # run before each test
    @api_instance = EjabberdHttpClient::SharedRosterGroupApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SharedRosterGroupApi' do
    it 'should create an instance of SharedRosterGroupApi' do
      expect(@api_instance).to be_instance_of(EjabberdHttpClient::SharedRosterGroupApi)
    end
  end

  # unit tests for srg_create
  # Create a Shared Roster Group.
  # @param [Hash] opts the optional parameters
  # @option opts [SrgCreateRequest] :srg_create_request
  # @return [Integer]
  describe 'srg_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for srg_delete
  # Delete a Shared Roster Group.
  # @param [Hash] opts the optional parameters
  # @option opts [SrgDeleteRequest] :srg_delete_request
  # @return [Integer]
  describe 'srg_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for srg_get_info
  # Get info of a Shared Roster Group.
  # @param [Hash] opts the optional parameters
  # @option opts [SrgDeleteRequest] :srg_delete_request
  # @return [Array<SrgGetInfo200ResponseInner>]
  describe 'srg_get_info test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for srg_get_members
  # Get members of a Shared Roster Group.
  # @param [Hash] opts the optional parameters
  # @option opts [SrgDeleteRequest] :srg_delete_request
  # @return [Array<String>]
  describe 'srg_get_members test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for srg_list
  # List the Shared Roster Groups in a host.
  # @param [Hash] opts the optional parameters
  # @option opts [ConnectedUsersVHostRequest] :connected_users_v_host_request
  # @return [Array<String>]
  describe 'srg_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for srg_user_add
  # Add the JID user@host to a Shared Roster Group.
  # @param [Hash] opts the optional parameters
  # @option opts [SrgUserAddRequest] :srg_user_add_request
  # @return [Integer]
  describe 'srg_user_add test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for srg_user_del
  # Delete the JID user@host from a Shared Roster Group.
  # @param [Hash] opts the optional parameters
  # @option opts [SrgUserAddRequest] :srg_user_add_request
  # @return [Integer]
  describe 'srg_user_del test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
