=begin
#OpenAPI Documentation for Ejabberd HTTP APIs

#APIs for managing Ejabberd server

The version of the OpenAPI document: 1.0.0


OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for EjabberdHttpClient::StanzaApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StanzaApi' do
  before do
    # run before each test
    @api_instance = EjabberdHttpClient::StanzaApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StanzaApi' do
    it 'should create an instance of StanzaApi' do
      expect(@api_instance).to be_instance_of(EjabberdHttpClient::StanzaApi)
    end
  end

  # unit tests for privacy_set
  # Send a IQ set privacy stanza for a local account.
  # @param [Hash] opts the optional parameters
  # @option opts [PrivacySetRequest] :privacy_set_request
  # @return [Integer]
  describe 'privacy_set test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_message
  # Send a message to a local or remote bare of full JID.
  # @param [Hash] opts the optional parameters
  # @option opts [SendMessageRequest] :send_message_request
  # @return [Integer]
  describe 'send_message test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_stanza
  # Send a stanza; provide From JID and valid To JID.
  # @param [Hash] opts the optional parameters
  # @option opts [SendStanzaRequest] :send_stanza_request
  # @return [Integer]
  describe 'send_stanza test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_stanza_c2_s
  # Send a stanza from an existing C2S session.
  # @param [Hash] opts the optional parameters
  # @option opts [SendStanzaC2SRequest] :send_stanza_c2_s_request
  # @return [Integer]
  describe 'send_stanza_c2_s test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
