=begin
#OpenAPI Documentation for Ejabberd HTTP APIs

#APIs for managing Ejabberd server

The version of the OpenAPI document: 1.0.0


OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for EjabberdHttpClient::StatisticsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StatisticsApi' do
  before do
    # run before each test
    @api_instance = EjabberdHttpClient::StatisticsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StatisticsApi' do
    it 'should create an instance of StatisticsApi' do
      expect(@api_instance).to be_instance_of(EjabberdHttpClient::StatisticsApi)
    end
  end

  # unit tests for connected_users_number
  # Get the number of established sessions.
  # @param [Hash] opts the optional parameters
  # @return [ConnectedUsersNumber200Response]
  describe 'connected_users_number test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_outgoing_s2s_number
  # Number of outgoing s2s connections on the node.
  # @param [Hash] opts the optional parameters
  # @return [GetOutgoingS2sNumber200Response]
  describe 'get_outgoing_s2s_number test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_stats
  # Get statistical value - registeredusers, onlineusers, onlineusersnode, uptimeseconds, processes.
  # @param [Hash] opts the optional parameters
  # @option opts [GetStatsRequest] :get_stats_request
  # @return [GetStats200Response]
  describe 'get_stats test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_stats_host
  # Get statistical value for this host - registeredusers, onlineusers.
  # @param [Hash] opts the optional parameters
  # @option opts [GetStatsHostRequest] :get_stats_host_request
  # @return [GetStats200Response]
  describe 'get_stats_host test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_status_num
  # Number of logged users with a specific status.
  # @param [Hash] opts the optional parameters
  # @option opts [GetStatusListRequest] :get_status_list_request
  # @return [GetStatusNum200Response]
  describe 'get_status_num test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_status_num_host
  # Number of logged users with a specific status in a host.
  # @param [Hash] opts the optional parameters
  # @option opts [GetStatusListHostRequest] :get_status_list_host_request
  # @return [GetStatusNum200Response]
  describe 'get_status_num_host test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for incoming_s2s_number
  # Number of incoming s2s connections on the node.
  # @param [Hash] opts the optional parameters
  # @return [IncomingS2sNumber200Response]
  describe 'incoming_s2s_number test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
