=begin
#OpenAPI Documentation for Ejabberd HTTP APIs

#APIs for managing Ejabberd server

The version of the OpenAPI document: 1.0.0


OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for EjabberdHttpClient::GetOfflineCount200Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe EjabberdHttpClient::GetOfflineCount200Response do
  let(:instance) { EjabberdHttpClient::GetOfflineCount200Response.new }

  describe 'test an instance of GetOfflineCount200Response' do
    it 'should create an instance of GetOfflineCount200Response' do
      expect(instance).to be_instance_of(EjabberdHttpClient::GetOfflineCount200Response)
    end
  end
  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
