=begin
#OpenAPI Documentation for Ejabberd HTTP APIs

#APIs for managing Ejabberd server

The version of the OpenAPI document: 1.0.0


OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for EjabberdHttpClient::ListMucOnlineRoomsByRegexRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe EjabberdHttpClient::ListMucOnlineRoomsByRegexRequest do
  let(:instance) { EjabberdHttpClient::ListMucOnlineRoomsByRegexRequest.new }

  describe 'test an instance of ListMucOnlineRoomsByRegexRequest' do
    it 'should create an instance of ListMucOnlineRoomsByRegexRequest' do
      expect(instance).to be_instance_of(EjabberdHttpClient::ListMucOnlineRoomsByRegexRequest)
    end
  end
  describe 'test attribute "service"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "regex"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
